name: Publish

on:
  push:
    branches: [dev, main]

jobs:
  integration-tests:
    runs-on: self-hosted
    steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: bun install

    - name: Run build
      run: bun run build
    
    - name: Run tests
      run: bun test
