name: Publish

on:
  push:
    branches: [dev, main]

jobs:
  publish:
    runs-on: self-hosted
    steps:
    # - name: Setup Bun
    #   uses: oven-sh/setup-bun@v2
    #   with:
    #     bun-version: latest

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: npm run install

    - name: Run build
      run: npm run build
    
    - name: Run tests
      run: npm run test
